In [2]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, n_features):
    super().__init__()

    self.linear = nn.Linear(n_features, 1) # linear(no_input , no_output)
    self.sigmoid = nn.Sigmoid()


  def forward(self , n_features):
    out = self.linear(n_features)
    out = self.sigmoid(out)





In [3]:
# CREATE DATASET
dataset_features = torch.rand(10 , 5)


# create model
model = Model(dataset_features.shape[1])

# call for forward pass
model(dataset_features)

In [4]:
model.linear.weight

Parameter containing:
tensor([[-0.3476, -0.2017, -0.3254, -0.2899,  0.3083]], requires_grad=True)

In [5]:
model.linear.bias

Parameter containing:
tensor([0.0682], requires_grad=True)

In [8]:
!pip install torchinfo


In [9]:
from torchinfo import summary

In [10]:
summary(model , input_size=(10 ,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    --                        --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Neural Network with hidden layers

In [15]:
class Model(nn.Module):

  def __init__(self, n_features):

    super().__init__()

    self.linear1 = nn.Linear(n_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, X_features):
    out = self.linear1(X_features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [26]:
# create dataset
dataset_features = torch.rand(10, 5)

# create model
model = Model(dataset_features.shape[1])

# call the forward pass
out = model(dataset_features)


model.linear1.weight


Parameter containing:
tensor([[-0.1843, -0.3422, -0.0423, -0.0964, -0.4092],
        [-0.3391, -0.1061,  0.3871, -0.2784, -0.1188],
        [-0.3946, -0.2554,  0.2231,  0.0185, -0.1279]], requires_grad=True)

In [27]:
model.linear1.bias

Parameter containing:
tensor([ 0.3552, -0.1607, -0.0215], requires_grad=True)

In [28]:
model.linear2.weight

Parameter containing:
tensor([[-0.0081, -0.1484,  0.1133]], requires_grad=True)

In [30]:
model.linear2.bias

Parameter containing:
tensor([0.3756], requires_grad=True)

### __init__ : Number of columns only Reserves memory and creates the fixed-size weight matrices.

### forward : Actual data tensor (Rows × Columns)Performs the mathematical operations using the data and the weights.

# sequential containers

In [32]:
class Model(nn.Module):

  def __init__(self, n_features):

    super().__init__()

    self.network = nn.Sequential(
        nn.Linear(n_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, X_features):
    out = self.network(X_features)

    return out

In [36]:
# create dataset
dataset_features = torch.rand(10, 5)

# create model
model = Model(dataset_features.shape[1])

# call the forward pass
out = model(dataset_features)
print(out)

tensor([[0.3426],
        [0.3730],
        [0.3460],
        [0.3464],
        [0.3287],
        [0.3606],
        [0.3332],
        [0.3621],
        [0.3645],
        [0.3378]], grad_fn=<SigmoidBackward0>)
