In [7]:
import torch
print(torch.__version__)

2.11.0+cu128


In [8]:
if torch.cuda.is_available():
  print("GPU available!!!")
  print(f"GPU: {torch.cuda.get_device_name(0)}")

else:
  print("No GPU available...using CPU")

GPU available!!!
GPU: Tesla T4


## Creating Tensor using empty

In [4]:
first_tensor = torch.empty(2 , 3)
print(first_tensor)

tensor([[-1.4306e+33,  4.5396e-41, -1.4306e+33],
        [ 4.5396e-41,  2.7123e-33,  0.0000e+00]])


### check type of tensor

In [5]:
print(type(first_tensor))

<class 'torch.Tensor'>


In [6]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.rand(2,3)

tensor([[0.8662, 0.1844, 0.4736],
        [0.3709, 0.3630, 0.3752]])

In [9]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.tensor([[2,3,4],[5,6,7]])


tensor([[2, 3, 4],
        [5, 6, 7]])

In [11]:
print(f"arrange : {torch.arange(0,10,2)}")

arrange : tensor([0, 2, 4, 6, 8])


In [12]:
print(f"linsspace : {torch.linspace(0,10,10)}")

linsspace : tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [13]:
print(f"identity : \n{torch.eye(6)}")

identity : 
tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])


In [14]:
print(f"torch fill with the given number:\n{torch.full((3,4),2)}")

torch fill with the given number:
tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]])


In [15]:
check_shape = torch.tensor([[1,2,3],[4,5,6]])
check_shape

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
check_shape.shape

torch.Size([2, 3])

In [17]:
torch.empty_like(check_shape)

tensor([[0, 0, 0],
        [0, 1, 0]])

In [18]:
torch.zeros_like(check_shape)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
check_shape.dtype

torch.int64

In [20]:
to_float = check_shape.to(torch.float64)
to_float

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

### clamp

In [21]:
torch.clamp(check_shape , min=2 , max=3)

tensor([[2, 2, 3],
        [3, 3, 3]])

### mean

In [22]:
torch.mean(to_float, dim=1)

tensor([2., 5.], dtype=torch.float64)

### median

In [23]:
torch.median(check_shape)

tensor(3)

### std dev

In [24]:
torch.std(to_float)

tensor(1.8708, dtype=torch.float64)

### variance

In [25]:
torch.var(to_float)

tensor(3.5000, dtype=torch.float64)

### product

In [26]:
torch.prod(to_float)

tensor(720., dtype=torch.float64)

### argmax

In [27]:
torch.argmax(to_float)

tensor(5)

### argmin

In [28]:
torch.argmin(to_float)

tensor(0)

## matrix multiplication

In [29]:
mat_1 = torch.randint(size=(2,3) , low=0 , high=10)

mat_2 = torch.randint(size=(3,2) , low=0 , high=10)


print(mat_1)
print(mat_2)

tensor([[2, 8, 8],
        [0, 4, 3]])
tensor([[8, 8],
        [4, 4],
        [1, 0]])


### multiply two matrices

In [30]:
torch.matmul(mat_1 , mat_2)

tensor([[56, 48],
        [19, 16]])

### dot product

In [31]:
vector_1 = torch.tensor([1,2,3])
vector_2 = torch.tensor([5,6,7])

In [32]:
torch.dot(vector_1 , vector_2)

tensor(38)

### transpose

In [33]:
torch.transpose(mat_1 , 0, 1)

tensor([[2, 0],
        [8, 4],
        [8, 3]])

### determinant

In [34]:
mat_det = torch.tensor([[1,2],[5,6]] , dtype=torch.float64)
mat_det

tensor([[1., 2.],
        [5., 6.]], dtype=torch.float64)

In [35]:
torch.det(mat_det)

tensor(-4., dtype=torch.float64)

### inverse

In [36]:
torch.inverse(mat_det)

tensor([[-1.5000,  0.5000],
        [ 1.2500, -0.2500]], dtype=torch.float64)

### comaprison operations

In [37]:
i = torch.randint(size=(2,3) , low=0 , high=10 , dtype=torch.float64)

j = torch.randint(size=(2,3) , low=0 , high=10)

print(i)
print(j)

tensor([[4., 3., 8.],
        [7., 4., 6.]], dtype=torch.float64)
tensor([[0, 1, 9],
        [9, 8, 0]])


In [38]:
  # less than
i < j

# greater than

# greater or equal

# less or equal

# not equal to


tensor([[False, False,  True],
        [ True,  True, False]])

## special functions

### LOG

In [39]:
torch.log(i)

tensor([[1.3863, 1.0986, 2.0794],
        [1.9459, 1.3863, 1.7918]], dtype=torch.float64)

### exponent

In [40]:
torch.exp(i)

tensor([[  54.5982,   20.0855, 2980.9580],
        [1096.6332,   54.5982,  403.4288]], dtype=torch.float64)

### sqrt

In [41]:
torch.sqrt(i)

tensor([[2.0000, 1.7321, 2.8284],
        [2.6458, 2.0000, 2.4495]], dtype=torch.float64)

### softmax

In [42]:
# input has to be float or long
torch.softmax(i , dim=0)

tensor([[0.0474, 0.2689, 0.8808],
        [0.9526, 0.7311, 0.1192]], dtype=torch.float64)

### sigmoid

In [43]:
torch.sigmoid(i)

tensor([[0.9820, 0.9526, 0.9997],
        [0.9991, 0.9820, 0.9975]], dtype=torch.float64)

### relu

In [44]:
torch.relu(i)

tensor([[4., 3., 8.],
        [7., 4., 6.]], dtype=torch.float64)

# Inplace operations

In [45]:
ten_1 = torch.randint(size=(2,3) , low=0 , high=10 , dtype=torch.float64)
ten_2 = torch.randint(size=(2,3) , low=0 , high=10 , dtype=torch.float64)

print(ten_1)
print(ten_2)

tensor([[7., 0., 0.],
        [9., 5., 7.]], dtype=torch.float64)
tensor([[3., 9., 4.],
        [0., 5., 7.]], dtype=torch.float64)


In [46]:
ten_1 + ten_2

tensor([[10.,  9.,  4.],
        [ 9., 10., 14.]], dtype=torch.float64)

In [47]:
# instead of doing ten_1 + ten_2 which will store this operation in another tensor and will take alot
# if our dataset is massive or we use the ten_1 to store the result

ten_1.add_(ten_2)

tensor([[10.,  9.,  4.],
        [ 9., 10., 14.]], dtype=torch.float64)

In [48]:
ten_1

tensor([[10.,  9.,  4.],
        [ 9., 10., 14.]], dtype=torch.float64)

## this inplace operation will work for all functions like : relu_() and what ever function you can you we can inplace it and they are permanent changes once inplaced

### just write _ infront of any function it will work as inplace operation

In [49]:
a = torch.rand(2,3)
a

tensor([[0.6476, 0.3430, 0.3182],
        [0.5261, 0.0447, 0.5123]])

In [50]:
b = a

In [51]:
a[0][0] = 0

In [52]:
a

tensor([[0.0000, 0.3430, 0.3182],
        [0.5261, 0.0447, 0.5123]])

In [53]:
b

tensor([[0.0000, 0.3430, 0.3182],
        [0.5261, 0.0447, 0.5123]])

In [54]:
id(a)

139138554383968

In [55]:
id(b)

139138554383968

In [56]:
b = a.clone()

In [57]:
a

tensor([[0.0000, 0.3430, 0.3182],
        [0.5261, 0.0447, 0.5123]])

In [58]:
b

tensor([[0.0000, 0.3430, 0.3182],
        [0.5261, 0.0447, 0.5123]])

In [59]:
# now change in a and check b will change or not as we use clone it will not change

a[0][0] = 3

In [60]:
a

tensor([[3.0000, 0.3430, 0.3182],
        [0.5261, 0.0447, 0.5123]])

In [61]:
b

tensor([[0.0000, 0.3430, 0.3182],
        [0.5261, 0.0447, 0.5123]])

In [62]:
id(a)

139138554383968

In [63]:
id(b)

139138554391408

# Tensor operation on GPU

In [64]:
torch.cuda.is_available()

True

In [65]:
device = torch.device('cuda')

In [66]:
import time

size = 10000

cpu_mat_1 = torch.randn(size , size)
cpu_mat_2 = torch.randn(size , size)


cpu_start_time = time.time()
result = torch.matmul(cpu_mat_1 , cpu_mat_2)
cpu_end_time = time.time() - cpu_start_time

print(f"Time on CPU : {cpu_end_time}")


gpu_mat_1 = cpu_mat_1.to('cuda')
gpu_mat_2 = cpu_mat_2.to('cuda')


gpu_start_time = time.time()
gpu_result = torch.matmul(gpu_mat_1 , gpu_mat_2)
torch.cuda.synchronize()
gpu_end_time = time.time() - gpu_start_time

print(f"Time on GPU : {gpu_end_time:.4f}")

print(f"CPU : {gpu_end_time / cpu_end_time}")
print(f"GPU : {cpu_end_time / gpu_end_time}")

Time on CPU : 16.394442319869995
Time on GPU : 0.6870
CPU : 0.0419073989713259
GPU : 23.862134719556927


## reshaping tensors




In [67]:
matrix = torch.ones(4,4)

In [68]:
matrix

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [69]:
matrix.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [70]:
matrix.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [71]:
res = torch.rand(2,3,4)

In [72]:
res

tensor([[[0.9319, 0.8348, 0.8722, 0.0954],
         [0.0307, 0.7172, 0.4986, 0.0144],
         [0.7610, 0.4741, 0.5713, 0.1198]],

        [[0.2450, 0.5691, 0.8353, 0.1892],
         [0.4455, 0.4799, 0.3206, 0.2995],
         [0.3521, 0.5425, 0.0926, 0.6088]]])

In [73]:
permute = res.permute(2,1,0)


In [74]:
permute

tensor([[[0.9319, 0.2450],
         [0.0307, 0.4455],
         [0.7610, 0.3521]],

        [[0.8348, 0.5691],
         [0.7172, 0.4799],
         [0.4741, 0.5425]],

        [[0.8722, 0.8353],
         [0.4986, 0.3206],
         [0.5713, 0.0926]],

        [[0.0954, 0.1892],
         [0.0144, 0.2995],
         [0.1198, 0.6088]]])

In [75]:
permute.shape

torch.Size([4, 3, 2])

## unsqueeze

In [76]:
cnn = torch.rand(226,226,3)

In [77]:
cnn.unsqueeze(0).shape # adds a dimension where you want to add now i need index 0 to add a dimension

torch.Size([1, 226, 226, 3])

## squeeze

In [78]:
# opposite of unsqueeze

squeeze_check = torch.rand(1 , 9)

In [79]:
squeeze_check.squeeze(0).shape


# it works when row is 1

torch.Size([9])

# AUTOGRAD

In [81]:
x = torch.tensor(3.0 , requires_grad=True)

In [82]:
y = x**2

In [83]:
x

tensor(3., requires_grad=True)

In [84]:
y.backward()

In [86]:
x.grad

tensor(6.)

In [87]:
z = torch.sin(y)

In [88]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [9]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

w = torch.tensor(1.0)
b = torch.tensor(0.0)

In [10]:
def binary_cross_entropy_loss(target , prediction):
  epsilon = 1e-8
  prediction = torch.clamp(prediction , epsilon , 1 - epsilon) # torch.clamp(input, min, max) If model predicts a probability of exactly 0.0 or 1.0 and turns out to be wrong so it should be b/w...

  return -(target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction))


## forward pass

In [11]:
z = w * x + b

In [12]:
y_pred = torch.sigmoid(z)

In [13]:
loss = binary_cross_entropy_loss(y , y_pred)

# backward pass

In [18]:
dloss_dy_pred = (y_pred - y) / y_pred*(1 - y_pred)

In [19]:
dy_pred_dz = y_pred * (1 - y_pred)


In [21]:
dz_dw = x
dz_db = 1

In [22]:
dl_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dl_db = dloss_dy_pred * dy_pred_dz * dz_db

In [23]:
print(f"loss wrt weight : {dl_dw}")
print(f"loss wrt bias : {dl_db}")

loss wrt weight : 1.0115162695001345e-05
loss wrt bias : 1.5097258483365295e-06
